### ISSUE TITLE
RuntimeError: DataLoader worker (pid(s)15680)exited unexpectedly

### ISSUE THREAD

**Issue by Zeyu1226-mt** [AcherStyx/CoCap#13]
When run the code on MSVD，I met this problem. Could you please help me solve this problem???

**Comment by Yaojie-Shen** [comment]
Based on the error message you provided, it's unclear where exactly the problem lies.
The most likely reason is that you haven't correctly converted the video into H.264 format. You could try reading all the videos first to check if all the videos in the dataset can be read correctly (follow the README in https://github.com/acherstyx/Compressed-Video-Reader).
